//
//  PokemonAbilityDefinition.swift
//  PokedexAbility
//
//  Created by elmetal on 2026/05/06
//
//

import Foundation

protocol PokemonAbilityDefinition: Sendable {
    static var ability: PokemonAbility { get }

    static func name(locale: Locale) -> String
    static func effectDescription(generation: PokemonGeneration, locale: Locale) -> String
}

extension PokemonAbilityDefinition {
    static func matchesName(_ value: String, locale: Locale) -> Bool {
        let input = value.trimmingCharacters(in: .whitespacesAndNewlines)

        return name(locale: locale).localizedStandardCompare(input) == .orderedSame
            || ability.rawValue.localizedStandardCompare(input) == .orderedSame
    }
}

enum PokemonAbilityDefinitions {
    static let all: [any PokemonAbilityDefinition.Type] = [
        Stench.self,
        Drizzle.self,
        SpeedBoost.self,
        BattleArmor.self,
        Sturdy.self,
        Damp.self,
        Limber.self,
        SandVeil.self,
        Static.self,
        VoltAbsorb.self,
        WaterAbsorb.self,
        Oblivious.self,
        CloudNine.self,
        CompoundEyes.self,
        Insomnia.self,
        ColorChange.self,
        Immunity.self,
        FlashFire.self,
        ShieldDust.self,
        OwnTempo.self,
        SuctionCups.self,
        Intimidate.self,
        ShadowTag.self,
        RoughSkin.self,
        WonderGuard.self,
        Levitate.self,
        EffectSpore.self,
        Synchronize.self,
        ClearBody.self,
        NaturalCure.self,
        LightningRod.self,
        SereneGrace.self,
        SwiftSwim.self,
        Chlorophyll.self,
        Illuminate.self,
        Trace.self,
        HugePower.self,
        PoisonPoint.self,
        InnerFocus.self,
        MagmaArmor.self,
        WaterVeil.self,
        MagnetPull.self,
        Soundproof.self,
        RainDish.self,
        SandStream.self,
        Pressure.self,
        ThickFat.self,
        EarlyBird.self,
        FlameBody.self,
        RunAway.self,
        KeenEye.self,
        HyperCutter.self,
        Pickup.self,
        Truant.self,
        Hustle.self,
        CuteCharm.self,
        Plus.self,
        Minus.self,
        Forecast.self,
        StickyHold.self,
        ShedSkin.self,
        Guts.self,
        MarvelScale.self,
        LiquidOoze.self,
        Overgrow.self,
        Blaze.self,
        Torrent.self,
        Swarm.self,
        RockHead.self,
        Drought.self,
        ArenaTrap.self,
        VitalSpirit.self,
        WhiteSmoke.self,
        PurePower.self,
        ShellArmor.self,
        Cacophony.self,
        AirLock.self,
        Adaptability.self,
        Aftermath.self,
        AngerPoint.self,
        Anticipation.self,
        BadDreams.self,
        Download.self,
        DrySkin.self,
        Filter.self,
        FlowerGift.self,
        Forewarn.self,
        Frisk.self,
        Gluttony.self,
        Heatproof.self,
        HoneyGather.self,
        Hydration.self,
        IceBody.self,
        IronFist.self,
        Klutz.self,
        LeafGuard.self,
        MagicGuard.self,
        MoldBreaker.self,
        MotorDrive.self,
        Multitype.self,
        NoGuard.self,
        Normalize.self,
        PoisonHeal.self,
        QuickFeet.self,
        Reckless.self,
        Rivalry.self,
        Scrappy.self,
        Simple.self,
        SkillLink.self,
        SlowStart.self,
        Sniper.self,
        SnowCloak.self,
        SnowWarning.self,
        SolarPower.self,
        SolidRock.self,
        Stall.self,
        Steadfast.self,
        StormDrain.self,
        SuperLuck.self,
        TangledFeet.self,
        Technician.self,
        TintedLens.self,
        Unaware.self,
        Unburden.self,
        Analytic.self,
        BigPecks.self,
        Contrary.self,
        CursedBody.self,
        Defeatist.self,
        Defiant.self,
        FlareBoost.self,
        FriendGuard.self,
        Harvest.self,
        Healer.self,
        HeavyMetal.self,
        Illusion.self,
        Imposter.self,
        Infiltrator.self,
        IronBarbs.self,
        Justified.self,
        LightMetal.self,
        MagicBounce.self,
        Moody.self,
        Moxie.self,
        Multiscale.self,
        Mummy.self,
        Overcoat.self,
        Pickpocket.self,
        PoisonTouch.self,
        Prankster.self,
        Rattled.self,
        Regenerator.self,
        SandForce.self,
        SandRush.self,
        SapSipper.self,
        SheerForce.self,
        Telepathy.self,
        Teravolt.self,
        ToxicBoost.self,
        Turboblaze.self,
        Unnerve.self,
        VictoryStar.self,
        WeakArmor.self,
        WonderSkin.self,
        ZenMode.self,
        Aerilate.self,
        AromaVeil.self,
        AuraBreak.self,
        Bulletproof.self,
        CheekPouch.self,
        Competitive.self,
        DarkAura.self,
        DeltaStream.self,
        DesolateLand.self,
        FairyAura.self,
        FlowerVeil.self,
        FurCoat.self,
        GaleWings.self,
        Gooey.self,
        GrassPelt.self,
        Magician.self,
        MegaLauncher.self,
        ParentalBond.self,
        Pixilate.self,
        PrimordialSea.self,
        Protean.self,
        Refrigerate.self,
        StanceChange.self,
        StrongJaw.self,
        SweetVeil.self,
        Symbiosis.self,
        ToughClaws.self,
    ]

    static func definition(for ability: PokemonAbility) -> (any PokemonAbilityDefinition.Type)? {
        all.first { $0.ability == ability }
    }
}
